### ISSUE TITLE
Release available?

### ISSUE THREAD

**Issue by NeoP5** [tmyroadctfig/icloud4j#3]
Hello,
first of all "Nice Work!" :D

i want to include this library into one of my projects which is based on maven.
Is there any release of this lib or do ich have build and include it my own?

It would be cool to have this mavenized and available via e.g. maven-central.

Best,
Neo

**Comment by tmyroadctfig** [comment]
Ni Neo,

Thanks :)

I agree, getting this up on maven-central is a good idea, and would probably help out the project which I'm using it in. I'll try to investigate that next week. Until then the best way to package it is by running gradlew jar.

Cheers,
Luke

**Comment by NeoP5** [comment]
Hello @tmyroadctfig ,

sorry but i am running on maven. Right now i dont have any need to go for gradle.
The release is nice. Thank you very much for that.

As you might see I create a fork of your project.
I will create a pull request to your project soon.
I made the following changed right now:
- mavenised project
- created gson compliant model-classes (replacing existing ones)
- on ICloudException prevent StackTrace by adding the cause-/root-exception
- some small stuff
- mocked junit tests

Will commit it soon after testing.
Hope you will like it...

Best,
Neo

**Comment by tmyroadctfig** [comment]
Hi Neo,

Please don't switch the build system to maven, it will only complicate merging going forward. I've uploaded the gradle wrapper in the latest commits, so to build the project all you need to do is run 'gradelw jar' from the project directory.

The rest of the changes sound fine; I look forwards to reviewing the pull request once you're done.

v1.6 is now uploaded here: https://search.maven.org/#artifactdetails%7Ccom.github.tmyroadctfig%7Cicloud4j%7C1.6%7Cjar

So I'll close off this issue for now.

Cheers, Luke
