### ISSUE TITLE
What is client id 

### ISSUE THREAD

**Issue by deepakkumarrai** [tmyroadctfig/icloud4j#5]
Hi @tmyroadctfig ,

Please clarify to me, What is client id and how can I get it.

**Comment by tmyroadctfig** [comment]
I just used a random GUID in the code I'm using this library from. Here is how they do it over in the original library:
https://github.com/picklepete/pyicloud/blob/ced8e83a40764438b9f0de7f441b932411aaac97/pyicloud/base.py#L123

**Comment by deepakkumarrai** [comment]
Thanks @tmyroadctfig
